---

- hosts: "all"
  become: True
  become_user: root

  tasks:
  - name: "Install libselinux-python on all servers"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - libselinux-python
      - libselinux-python
      - libselinux-python

  - name: "Installing epel repo"
    shell: rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    args:
      warn: False
  
  - name: "Setting Selinux To Permissive"
    selinux:
      policy: targeted
      state: permissive

  - name: "Setting Soft Open File Limits"
    pam_limits:
      domain: '*'
      limit_type: soft
      limit_item: nofile
      value: 65535

  - name: "Setting Hard Open File Limits"
    pam_limits:
      domain: '*'
      limit_type: hard
      limit_item: nofile
      value: 65535

  - name: "Adjusting OS Swappiness"
    sysctl:
      name: vm.swappiness
      value: 1
      state: present

  - name: "Installing New MariaDB Repo"
    template:
      src: /tmp/MariaDB_xpand.repo
      dest: /etc/yum.repos.d/MariaDB_xpand.repo

  - name: "Removing mariadb-libs"
    yum:
      name: 'mariadb-libs'
      state: absent

  - name: "Upgrading All Packages"
    yum:
      name: '*'
      state: latest

  - name: Installing Some Basic Packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - nano
      - epel-release
      - pigz
      - socat

- hosts: "xpand"
  become: True
  become_user: root

  tasks:
  - name: Installing Some Basic Packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - nano

  - name: "Uncompress Xpand"
    command: tar -xvzf 



- hosts: "mariadb"
  become: True
  become_user: root

  tasks:

  - name: "Installing MariaDB Server"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - MariaDB-xpand-engine

  - name: Insert a line at the end of a file.
    blockinfile:
     dest: /etc/my.cnf.d/xpand.cnf
     block: |
      plugin-maturity=beta
      xpand_hosts=10.0.2.11,10.0.3.11,10.0.4.11
      xpand_port=3306
      xpand_username=root

  - name: "Creating MySQL Log Directory"
    file:
      path: /var/log/mysql
      state: directory
      mode: 0755
      owner: mysql
      group: mysql

  - name: "Creating/Updating server.cnf"
    template:
      src: templates/general_xpand.j2
      dest: /etc/my.cnf.d/server.cnf

  - name: "Installing/Updating timeouts.conf Template"
    template:
      src: templates/timeouts.j2
      dest: /etc/systemd/system/mariadb.service.d/timeouts.conf

  - name: "Reloading Systemd"
    command: systemctl daemon-reload

  - name: "Stopping MariaDB"
    systemd:
      name: mysql
      enabled: yes
      state: stopped

- hosts: "mariadb1"
  become: True
  become_user: root

  tasks:

  - name: "Starting MariaDB on Master"
    systemd:
      name: mysql
      enabled: yes
      state: restarted

- hosts: xpand
  become: True
  become_user: root

  tasks:

  - name: "Installing bzip2"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - bzip2

- hosts: "mariadb2,mariadb3"
  become: True
  become_user: root

  tasks:

  - name: "Starting MariaDB on Slaves"
    systemd:
      name: mysql
      enabled: yes
      state: restarted

- hosts: "maxscale"
  become: True
  become_user: root

  tasks:

  - name: "Installing MaxScale"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - maxscale

  - name: "Removing Old Secrets"
    file:
      path: /var/lib/maxscale/.secrets
      state: absent

  - name: "Creating New Secrets"
    command: /bin/maxkeys /var/lib/maxscale/

  - name: "Changing Owner Of Secrets"
    file:
      path: /var/lib/maxscale/.secrets
      state: touch
      owner: maxscale
      group: maxscale

  - name: "Creating Encrypted Password"
    command: /bin/maxpasswd /var/lib/maxscale/ {{ maxscale_pass }}
    register: hexadecimal

  - name: "Copying maxscale.cnf"
    template:
      src: templates/maxscale.j2
      dest: /etc/maxscale.cnf

  - name: "Creating MaxScale Extra Folder"
    file:
      path: /etc/maxscale.cnf.d/
      state: directory
      owner: maxscale
      group: maxscale

  - name: "Restarting MaxScale"
    systemd:
      name: maxscale
      enabled: True
      state: restarted
