---

- hosts: "all"
  become: True
  become_user: root
  vars_files:
    - 'variables.yml'

  tasks:
  - name: "Install libselinux-python on all servers"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - libselinux-python
      
  - name: "Installing epel repo"
    shell: rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    args:
      warn: False

  - name: "Removing mariadb-libs"
    yum:
      name: 'mariadb-libs'
      state: absent

  - name: "Setting Selinux To Permissive"
    selinux:
      policy: targeted
      state: permissive

  - name: "Setting Soft Open File Limits"
    pam_limits:
      domain: '*'
      limit_type: soft
      limit_item: nofile
      value: 65535

  - name: "Setting Hard Open File Limits"
    pam_limits:
      domain: '*'
      limit_type: hard
      limit_item: nofile
      value: 65535

  - name: "Adjusting OS Swappiness"
    sysctl:
      name: vm.swappiness
      value: 1
      state: present

  - name: "Upgrading All Packages"
    yum:
      name: '*'
      state: latest

  - name: Installing Some Basic Packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - wget
      - nano
      - epel-release
      - pigz
      - socat
      - python2
      - python3
      - python2-pip
      - python3-pip

  - name: "Installing PyMySQL Module"
    pip:
      name: PyMySQL


- hosts: "xpand"
  become: True
  become_user: root

  tasks:
  - name: Installing Some Basic Packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - nano


- hosts: "mariadb"
  become: True
  become_user: root
  vars_files:
    - 'variables.yml'

  tasks:

  - name: "Installing New MariaDB Repo"
    template:
      src: /tmp/MariaDB_xpand.repo
      dest: /etc/yum.repos.d/MariaDB_xpand.repo

  - name: "Installing MariaDB Server"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - MariaDB-xpand-engine

  - name: Insert a line at the end of a file.
    blockinfile:
     dest: /etc/my.cnf.d/xpand.cnf
     block: |
      plugin-maturity=beta
      xpand_hosts=10.0.2.11,10.0.3.11,10.0.4.11
      xpand_port=3306
      xpand_username=root

  - name: "Creating MySQL Log Directory"
    file:
      path: /var/log/mysql
      state: directory
      mode: 0755
      owner: mysql
      group: mysql

  - name: "Creating/Updating server.cnf"
    template:
      src: templates/general_xpand.j2
      dest: /etc/my.cnf.d/server.cnf

  - name: "Installing/Updating timeouts.conf Template"
    template:
      src: templates/timeouts.j2
      dest: /etc/systemd/system/mariadb.service.d/timeouts.conf

  - name: "Enabling MariaDB Server"
    systemd:
      name: mariadb
      state: restarted
      enabled: yes
  - name: "Removing 'Test' Database If Exists"
    mysql_db:
      name: test
      state: absent
      login_unix_socket: '{{ mariadb_socket }}'

  - name: "Adding {{ demo_user }}@localhost User To Database"
    mysql_user:
      name: '{{ demo_user }}'
      host: 'localhost'
      password: '{{ demo_pass }}'
      update_password: on_create
      priv: '*.*:SELECT'
      state: present
      login_unix_socket: '{{ mariadb_socket }}'
    no_log: true

  - name: "Adding {{ demo_user }}@10.% User To Database"
    mysql_user:
      name: '{{ demo_user }}'
      host: '10.%'
      password: '{{ demo_pass }}'
      update_password: on_create
      priv: '*.*:SELECT'
      state: present
      login_unix_socket: '{{ mariadb_socket }}'
    no_log: true

  - name: "Adding '{{ repli_user }}'@'%'"
    mysql_user:
      name: '{{ repli_user }}'
      host: '%'
      password: '{{ repli_pass }}'
      update_password: on_create
      priv: '*.*:REPLICATION CLIENT,REPLICATION SLAVE'
      state: present
      login_unix_socket: '{{ mariadb_socket }}'
    no_log: true

  - name: "Adding '{{ repli_user }}'@'localhost'"
    mysql_user:
      name: '{{ repli_user }}'
      host: 'localhost'
      password: '{{ repli_pass }}'
      update_password: on_create
      priv: '*.*:REPLICATION CLIENT,REPLICATION SLAVE'
      state: present
      login_unix_socket: '{{ mariadb_socket }}'
    no_log: true

  - name: "Reloading Systemd"
    command: systemctl daemon-reload

  - name: "Stopping MariaDB"
    systemd:
      name: mysql
      enabled: yes
      state: stopped

- hosts: "mariadb1"
  become: True
  become_user: root

  tasks:

  - name: "Starting MariaDB on Master"
    systemd:
      name: mysql
      enabled: yes
      state: restarted

- hosts: xpand
  become: True
  become_user: root
  vars_files:
    - '/tmp/file_variables.yml'

  tasks:

  - name: "Installing bzip2"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - bzip2

  - name: "Downloading Xpand"
    get_url:
     url: {{ xpand_url }}
     dest: /tmp/xpand.tar.bz2
     mode: '0777'

    
  - name: Uncompressing Xpand binaries
    command: tar xvf /tmp/xpand.tar.bz2 -C /tmp
    
  - name: "Startng Xpand"
    command: /tmp/clustrix-9.3_beta_6.el7/clxnode_install.py --yes


- hosts: "xpand1"
  become: True
  become_user: root
  vars_files:
    - 'variables.yml'

  tasks:
  - name: "Copying xpand.key"
    template:
      src: /tmp/xpand.key
      dest: /tmp/xpand.key

- hosts: "mariadb2,mariadb3"
  become: True
  become_user: root
  vars_files:
    - 'variables.yml'

  tasks:
  - name: "Setting Replicas Read Only"
    mysql_variables:
      variable: read_only
      value: '1'
      login_unix_socket: '{{ mariadb_socket }}'

  - name: "Stopping Replicas"
    mysql_replication:
      mode: stopslave
      login_unix_socket: '{{ mariadb_socket }}'

  - name: "Setting Primary Info"
    mysql_replication:
      mode: changemaster
      master_host: '{{ mdb1 }}'
      master_user: '{{ repli_user }}'
      master_password: '{{ repli_pass }}'
      login_unix_socket: '{{ mariadb_socket }}'

  - name: "Converting to MariaDB GTID"
    command: mysql -e "CHANGE MASTER TO master_use_gtid=slave_pos";

  - name: "Starting Replicas"
    mysql_replication:
      mode: startslave
      login_unix_socket: '{{ mariadb_socket }}'




  - name: "Starting MariaDB on Slaves"
    systemd:
      name: mysql
      enabled: yes
      state: restarted
